// src/app.ts
import express2 from "express";
import cors from "cors";

// src/routes/index.ts
import { Router as Router5 } from "express";

// src/modules/User/user.route.ts
import { Router } from "express";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.1",
  "engineVersion": "55ae170b1ced7fc6ed07a15f110549408c501bb3",
  "activeProvider": "postgresql",
  "inlineSchema": 'generator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nenum Role {\n  CUSTOMER\n  PROVIDER\n  ADMIN\n}\n\nenum UserStatus {\n  ACTIVE\n  SUSPENDED\n}\n\nenum OrderStatus {\n  PENDING\n  ACCEPTED\n  PREPARING\n  DELIVERED\n  CANCELLED\n}\n\nmodel User {\n  id       String     @id @default(uuid())\n  email    String     @unique\n  password String\n  name     String?\n  role     Role       @default(CUSTOMER)\n  status   UserStatus @default(ACTIVE)\n\n  // Many to many relation \n  provider Provider?\n  orders   Order[]   @relation("CustomerOrders")\n  reviews  Review[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\n//*Provider Model \nmodel Provider {\n  id            String   @id @default(uuid())\n  resturentName String\n  cuisineTypes  String[]\n  location      String\n  isApproved    Boolean  @default(true)\n\n  userId String @unique\n  user   User   @relation(fields: [userId], references: [id])\n\n  meals  Meal[]\n  orders Order[] @relation("ProviderOrders")\n\n  createdAt DateTime @default(now())\n}\n\nmodel Category {\n  id       String  @id @default(uuid())\n  name     String\n  slug     String  @unique\n  isActive Boolean @default(true)\n\n  meals Meal[]\n\n  createdAt DateTime @default(now())\n}\n\nmodel Meal {\n  id          String   @id @default(uuid())\n  name        String\n  description String?\n  price       Float\n  image       String?\n  dietaryTags String[]\n  isAvailable Boolean  @default(true)\n\n  providerId String\n  provider   Provider @relation(fields: [providerId], references: [id])\n\n  categoryId String?\n  category   Category? @relation(fields: [categoryId], references: [id])\n\n  orderItems OrderItem[]\n  reviews    Review[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel Order {\n  id              String      @id @default(uuid())\n  customerId      String\n  providerId      String\n  totalAmount     Float\n  deliveryAddress String\n  paymentMethod   String      @default("COD")\n  status          OrderStatus @default(PENDING)\n\n  customer User     @relation("CustomerOrders", fields: [customerId], references: [id])\n  provider Provider @relation("ProviderOrders", fields: [providerId], references: [id])\n\n  items OrderItem[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel OrderItem {\n  id       String @id @default(uuid())\n  orderId  String\n  mealId   String\n  name     String\n  price    Float\n  quantity Int\n\n  order Order @relation(fields: [orderId], references: [id])\n  meal  Meal  @relation(fields: [mealId], references: [id])\n}\n\nmodel Review {\n  id      String  @id @default(uuid())\n  rating  Int\n  comment String?\n\n  mealId     String\n  customerId String\n\n  meal     Meal @relation(fields: [mealId], references: [id])\n  customer User @relation(fields: [customerId], references: [id])\n\n  createdAt DateTime @default(now())\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"provider","kind":"object","type":"Provider","relationName":"ProviderToUser"},{"name":"orders","kind":"object","type":"Order","relationName":"CustomerOrders"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Provider":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"resturentName","kind":"scalar","type":"String"},{"name":"cuisineTypes","kind":"scalar","type":"String"},{"name":"location","kind":"scalar","type":"String"},{"name":"isApproved","kind":"scalar","type":"Boolean"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"ProviderToUser"},{"name":"meals","kind":"object","type":"Meal","relationName":"MealToProvider"},{"name":"orders","kind":"object","type":"Order","relationName":"ProviderOrders"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"slug","kind":"scalar","type":"String"},{"name":"isActive","kind":"scalar","type":"Boolean"},{"name":"meals","kind":"object","type":"Meal","relationName":"CategoryToMeal"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Meal":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"image","kind":"scalar","type":"String"},{"name":"dietaryTags","kind":"scalar","type":"String"},{"name":"isAvailable","kind":"scalar","type":"Boolean"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"provider","kind":"object","type":"Provider","relationName":"MealToProvider"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToMeal"},{"name":"orderItems","kind":"object","type":"OrderItem","relationName":"MealToOrderItem"},{"name":"reviews","kind":"object","type":"Review","relationName":"MealToReview"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Order":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"totalAmount","kind":"scalar","type":"Float"},{"name":"deliveryAddress","kind":"scalar","type":"String"},{"name":"paymentMethod","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"OrderStatus"},{"name":"customer","kind":"object","type":"User","relationName":"CustomerOrders"},{"name":"provider","kind":"object","type":"Provider","relationName":"ProviderOrders"},{"name":"items","kind":"object","type":"OrderItem","relationName":"OrderToOrderItem"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"OrderItem":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"orderId","kind":"scalar","type":"String"},{"name":"mealId","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"order","kind":"object","type":"Order","relationName":"OrderToOrderItem"},{"name":"meal","kind":"object","type":"Meal","relationName":"MealToOrderItem"}],"dbName":null},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"mealId","kind":"scalar","type":"String"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"meal","kind":"object","type":"Meal","relationName":"MealToReview"},{"name":"customer","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","user","orderBy","cursor","provider","meals","_count","category","customer","items","order","meal","orderItems","reviews","orders","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Provider.findUnique","Provider.findUniqueOrThrow","Provider.findFirst","Provider.findFirstOrThrow","Provider.findMany","Provider.createOne","Provider.createMany","Provider.createManyAndReturn","Provider.updateOne","Provider.updateMany","Provider.updateManyAndReturn","Provider.upsertOne","Provider.deleteOne","Provider.deleteMany","Provider.groupBy","Provider.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Meal.findUnique","Meal.findUniqueOrThrow","Meal.findFirst","Meal.findFirstOrThrow","Meal.findMany","Meal.createOne","Meal.createMany","Meal.createManyAndReturn","Meal.updateOne","Meal.updateMany","Meal.updateManyAndReturn","Meal.upsertOne","Meal.deleteOne","Meal.deleteMany","_avg","_sum","Meal.groupBy","Meal.aggregate","Order.findUnique","Order.findUniqueOrThrow","Order.findFirst","Order.findFirstOrThrow","Order.findMany","Order.createOne","Order.createMany","Order.createManyAndReturn","Order.updateOne","Order.updateMany","Order.updateManyAndReturn","Order.upsertOne","Order.deleteOne","Order.deleteMany","Order.groupBy","Order.aggregate","OrderItem.findUnique","OrderItem.findUniqueOrThrow","OrderItem.findFirst","OrderItem.findFirstOrThrow","OrderItem.findMany","OrderItem.createOne","OrderItem.createMany","OrderItem.createManyAndReturn","OrderItem.updateOne","OrderItem.updateMany","OrderItem.updateManyAndReturn","OrderItem.upsertOne","OrderItem.deleteOne","OrderItem.deleteMany","OrderItem.groupBy","OrderItem.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","AND","OR","NOT","id","rating","comment","mealId","customerId","createdAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","orderId","name","price","quantity","providerId","totalAmount","deliveryAddress","paymentMethod","OrderStatus","status","updatedAt","description","image","dietaryTags","isAvailable","categoryId","has","hasEvery","hasSome","slug","isActive","every","some","none","resturentName","cuisineTypes","location","isApproved","userId","email","password","Role","role","UserStatus","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","push","increment","decrement","multiply","divide"]'),
  graph: "5wNGcA4EAAD0AQAgDQAA9QEAIA4AAOgBACCHAQAA8AEAMIgBAAAkABCJAQAA8AEAMIoBAQAAAAGPAUAA4wEAIZwBAQDxAQAhpAEAAPMBvQEipQFAAOMBACG4AQEAAAABuQEBAOEBACG7AQAA8gG7ASIBAAAAAQAgDQEAAOcBACAFAADkAQAgDgAA6AEAIIcBAADmAQAwiAEAAAMAEIkBAADmAQAwigEBAOEBACGPAUAA4wEAIbMBAQDhAQAhtAEAANsBACC1AQEA4QEAIbYBIADiAQAhtwEBAOEBACEBAAAAAwAgEgQAAPkBACAHAACBAgAgDAAA-gEAIA0AAPUBACCHAQAAgAIAMIgBAAAFABCJAQAAgAIAMIoBAQDhAQAhjwFAAOMBACGcAQEA4QEAIZ0BCAD3AQAhnwEBAOEBACGlAUAA4wEAIaYBAQDxAQAhpwEBAPEBACGoAQAA2wEAIKkBIADiAQAhqgEBAPEBACEHBAAArQMAIAcAALIDACAMAACvAwAgDQAArgMAIKYBAACCAgAgpwEAAIICACCqAQAAggIAIBIEAAD5AQAgBwAAgQIAIAwAAPoBACANAAD1AQAghwEAAIACADCIAQAABQAQiQEAAIACADCKAQEAAAABjwFAAOMBACGcAQEA4QEAIZ0BCAD3AQAhnwEBAOEBACGlAUAA4wEAIaYBAQDxAQAhpwEBAPEBACGoAQAA2wEAIKkBIADiAQAhqgEBAPEBACEDAAAABQAgAgAABgAwAwAABwAgCQUAAOQBACCHAQAA4AEAMIgBAAAJABCJAQAA4AEAMIoBAQDhAQAhjwFAAOMBACGcAQEA4QEAIa4BAQDhAQAhrwEgAOIBACEBAAAACQAgAwAAAAUAIAIAAAYAMAMAAAcAIAEAAAAFACALCgAA_wEAIAsAAP0BACCHAQAA_gEAMIgBAAANABCJAQAA_gEAMIoBAQDhAQAhjQEBAOEBACGbAQEA4QEAIZwBAQDhAQAhnQEIAPcBACGeAQIA_AEAIQIKAACxAwAgCwAAsAMAIAsKAAD_AQAgCwAA_QEAIIcBAAD-AQAwiAEAAA0AEIkBAAD-AQAwigEBAAAAAY0BAQDhAQAhmwEBAOEBACGcAQEA4QEAIZ0BCAD3AQAhngECAPwBACEDAAAADQAgAgAADgAwAwAADwAgAwAAAA0AIAIAAA4AMAMAAA8AIAEAAAANACALCAAA5wEAIAsAAP0BACCHAQAA-wEAMIgBAAATABCJAQAA-wEAMIoBAQDhAQAhiwECAPwBACGMAQEA8QEAIY0BAQDhAQAhjgEBAOEBACGPAUAA4wEAIQMIAACJAwAgCwAAsAMAIIwBAACCAgAgCwgAAOcBACALAAD9AQAghwEAAPsBADCIAQAAEwAQiQEAAPsBADCKAQEAAAABiwECAPwBACGMAQEA8QEAIY0BAQDhAQAhjgEBAOEBACGPAUAA4wEAIQMAAAATACACAAAUADADAAAVACABAAAADQAgAQAAABMAIA8EAAD5AQAgCAAA5wEAIAkAAPoBACCHAQAA9gEAMIgBAAAZABCJAQAA9gEAMIoBAQDhAQAhjgEBAOEBACGPAUAA4wEAIZ8BAQDhAQAhoAEIAPcBACGhAQEA4QEAIaIBAQDhAQAhpAEAAPgBpAEipQFAAOMBACEDBAAArQMAIAgAAIkDACAJAACvAwAgDwQAAPkBACAIAADnAQAgCQAA-gEAIIcBAAD2AQAwiAEAABkAEIkBAAD2AQAwigEBAAAAAY4BAQDhAQAhjwFAAOMBACGfAQEA4QEAIaABCAD3AQAhoQEBAOEBACGiAQEA4QEAIaQBAAD4AaQBIqUBQADjAQAhAwAAABkAIAIAABoAMAMAABsAIAEAAAAFACABAAAAGQAgAwAAABkAIAIAABoAMAMAABsAIAMAAAATACACAAAUADADAAAVACABAAAAGQAgAQAAABMAIAEAAAABACAOBAAA9AEAIA0AAPUBACAOAADoAQAghwEAAPABADCIAQAAJAAQiQEAAPABADCKAQEA4QEAIY8BQADjAQAhnAEBAPEBACGkAQAA8wG9ASKlAUAA4wEAIbgBAQDhAQAhuQEBAOEBACG7AQAA8gG7ASIEBAAArQMAIA0AAK4DACAOAACKAwAgnAEAAIICACADAAAAJAAgAgAAJQAwAwAAAQAgAwAAACQAIAIAACUAMAMAAAEAIAMAAAAkACACAAAlADADAAABACALBAAAqgMAIA0AAKwDACAOAACrAwAgigEBAAAAAY8BQAAAAAGcAQEAAAABpAEAAAC9AQKlAUAAAAABuAEBAAAAAbkBAQAAAAG7AQAAALsBAgEUAAApACAIigEBAAAAAY8BQAAAAAGcAQEAAAABpAEAAAC9AQKlAUAAAAABuAEBAAAAAbkBAQAAAAG7AQAAALsBAgEUAAArADABFAAAKwAwCwQAAJADACANAACSAwAgDgAAkQMAIIoBAQCIAgAhjwFAAIsCACGcAQEAigIAIaQBAACPA70BIqUBQACLAgAhuAEBAIgCACG5AQEAiAIAIbsBAACOA7sBIgIAAAABACAUAAAuACAIigEBAIgCACGPAUAAiwIAIZwBAQCKAgAhpAEAAI8DvQEipQFAAIsCACG4AQEAiAIAIbkBAQCIAgAhuwEAAI4DuwEiAgAAACQAIBQAADAAIAIAAAAkACAUAAAwACADAAAAAQAgGwAAKQAgHAAALgAgAQAAAAEAIAEAAAAkACAEBgAAiwMAICEAAI0DACAiAACMAwAgnAEAAIICACALhwEAAOkBADCIAQAANwAQiQEAAOkBADCKAQEAxQEAIY8BQADIAQAhnAEBAMcBACGkAQAA6wG9ASKlAUAAyAEAIbgBAQDFAQAhuQEBAMUBACG7AQAA6gG7ASIDAAAAJAAgAgAANgAwIAAANwAgAwAAACQAIAIAACUAMAMAAAEAIA0BAADnAQAgBQAA5AEAIA4AAOgBACCHAQAA5gEAMIgBAAADABCJAQAA5gEAMIoBAQAAAAGPAUAA4wEAIbMBAQDhAQAhtAEAANsBACC1AQEA4QEAIbYBIADiAQAhtwEBAAAAAQEAAAA6ACABAAAAOgAgAwEAAIkDACAFAADoAgAgDgAAigMAIAMAAAADACACAAA9ADADAAA6ACADAAAAAwAgAgAAPQAwAwAAOgAgAwAAAAMAIAIAAD0AMAMAADoAIAoBAACGAwAgBQAAhwMAIA4AAIgDACCKAQEAAAABjwFAAAAAAbMBAQAAAAG0AQAAhQMAILUBAQAAAAG2ASAAAAABtwEBAAAAAQEUAABBACAHigEBAAAAAY8BQAAAAAGzAQEAAAABtAEAAIUDACC1AQEAAAABtgEgAAAAAbcBAQAAAAEBFAAAQwAwARQAAEMAMAoBAADtAgAgBQAA7gIAIA4AAO8CACCKAQEAiAIAIY8BQACLAgAhswEBAIgCACG0AQAA7AIAILUBAQCIAgAhtgEgALgCACG3AQEAiAIAIQIAAAA6ACAUAABGACAHigEBAIgCACGPAUAAiwIAIbMBAQCIAgAhtAEAAOwCACC1AQEAiAIAIbYBIAC4AgAhtwEBAIgCACECAAAAAwAgFAAASAAgAgAAAAMAIBQAAEgAIAMAAAA6ACAbAABBACAcAABGACABAAAAOgAgAQAAAAMAIAMGAADpAgAgIQAA6wIAICIAAOoCACAKhwEAAOUBADCIAQAATwAQiQEAAOUBADCKAQEAxQEAIY8BQADIAQAhswEBAMUBACG0AQAA2wEAILUBAQDFAQAhtgEgANwBACG3AQEAxQEAIQMAAAADACACAABOADAgAABPACADAAAAAwAgAgAAPQAwAwAAOgAgCQUAAOQBACCHAQAA4AEAMIgBAAAJABCJAQAA4AEAMIoBAQAAAAGPAUAA4wEAIZwBAQDhAQAhrgEBAAAAAa8BIADiAQAhAQAAAFIAIAEAAABSACABBQAA6AIAIAMAAAAJACACAABVADADAABSACADAAAACQAgAgAAVQAwAwAAUgAgAwAAAAkAIAIAAFUAMAMAAFIAIAYFAADnAgAgigEBAAAAAY8BQAAAAAGcAQEAAAABrgEBAAAAAa8BIAAAAAEBFAAAWQAgBYoBAQAAAAGPAUAAAAABnAEBAAAAAa4BAQAAAAGvASAAAAABARQAAFsAMAEUAABbADAGBQAA2gIAIIoBAQCIAgAhjwFAAIsCACGcAQEAiAIAIa4BAQCIAgAhrwEgALgCACECAAAAUgAgFAAAXgAgBYoBAQCIAgAhjwFAAIsCACGcAQEAiAIAIa4BAQCIAgAhrwEgALgCACECAAAACQAgFAAAYAAgAgAAAAkAIBQAAGAAIAMAAABSACAbAABZACAcAABeACABAAAAUgAgAQAAAAkAIAMGAADXAgAgIQAA2QIAICIAANgCACAIhwEAAN8BADCIAQAAZwAQiQEAAN8BADCKAQEAxQEAIY8BQADIAQAhnAEBAMUBACGuAQEAxQEAIa8BIADcAQAhAwAAAAkAIAIAAGYAMCAAAGcAIAMAAAAJACACAABVADADAABSACABAAAABwAgAQAAAAcAIAMAAAAFACACAAAGADADAAAHACADAAAABQAgAgAABgAwAwAABwAgAwAAAAUAIAIAAAYAMAMAAAcAIA8EAADTAgAgBwAA1AIAIAwAANUCACANAADWAgAgigEBAAAAAY8BQAAAAAGcAQEAAAABnQEIAAAAAZ8BAQAAAAGlAUAAAAABpgEBAAAAAacBAQAAAAGoAQAA0gIAIKkBIAAAAAGqAQEAAAABARQAAG8AIAuKAQEAAAABjwFAAAAAAZwBAQAAAAGdAQgAAAABnwEBAAAAAaUBQAAAAAGmAQEAAAABpwEBAAAAAagBAADSAgAgqQEgAAAAAaoBAQAAAAEBFAAAcQAwARQAAHEAMAEAAAAJACAPBAAAuQIAIAcAALoCACAMAAC7AgAgDQAAvAIAIIoBAQCIAgAhjwFAAIsCACGcAQEAiAIAIZ0BCACVAgAhnwEBAIgCACGlAUAAiwIAIaYBAQCKAgAhpwEBAIoCACGoAQAAtwIAIKkBIAC4AgAhqgEBAIoCACECAAAABwAgFAAAdQAgC4oBAQCIAgAhjwFAAIsCACGcAQEAiAIAIZ0BCACVAgAhnwEBAIgCACGlAUAAiwIAIaYBAQCKAgAhpwEBAIoCACGoAQAAtwIAIKkBIAC4AgAhqgEBAIoCACECAAAABQAgFAAAdwAgAgAAAAUAIBQAAHcAIAEAAAAJACADAAAABwAgGwAAbwAgHAAAdQAgAQAAAAcAIAEAAAAFACAIBgAAsgIAICEAALUCACAiAAC0AgAgUwAAswIAIFQAALYCACCmAQAAggIAIKcBAACCAgAgqgEAAIICACAOhwEAANoBADCIAQAAfwAQiQEAANoBADCKAQEAxQEAIY8BQADIAQAhnAEBAMUBACGdAQgA1AEAIZ8BAQDFAQAhpQFAAMgBACGmAQEAxwEAIacBAQDHAQAhqAEAANsBACCpASAA3AEAIaoBAQDHAQAhAwAAAAUAIAIAAH4AMCAAAH8AIAMAAAAFACACAAAGADADAAAHACABAAAAGwAgAQAAABsAIAMAAAAZACACAAAaADADAAAbACADAAAAGQAgAgAAGgAwAwAAGwAgAwAAABkAIAIAABoAMAMAABsAIAwEAACwAgAgCAAArwIAIAkAALECACCKAQEAAAABjgEBAAAAAY8BQAAAAAGfAQEAAAABoAEIAAAAAaEBAQAAAAGiAQEAAAABpAEAAACkAQKlAUAAAAABARQAAIcBACAJigEBAAAAAY4BAQAAAAGPAUAAAAABnwEBAAAAAaABCAAAAAGhAQEAAAABogEBAAAAAaQBAAAApAECpQFAAAAAAQEUAACJAQAwARQAAIkBADAMBAAAoQIAIAgAAKACACAJAACiAgAgigEBAIgCACGOAQEAiAIAIY8BQACLAgAhnwEBAIgCACGgAQgAlQIAIaEBAQCIAgAhogEBAIgCACGkAQAAnwKkASKlAUAAiwIAIQIAAAAbACAUAACMAQAgCYoBAQCIAgAhjgEBAIgCACGPAUAAiwIAIZ8BAQCIAgAhoAEIAJUCACGhAQEAiAIAIaIBAQCIAgAhpAEAAJ8CpAEipQFAAIsCACECAAAAGQAgFAAAjgEAIAIAAAAZACAUAACOAQAgAwAAABsAIBsAAIcBACAcAACMAQAgAQAAABsAIAEAAAAZACAFBgAAmgIAICEAAJ0CACAiAACcAgAgUwAAmwIAIFQAAJ4CACAMhwEAANYBADCIAQAAlQEAEIkBAADWAQAwigEBAMUBACGOAQEAxQEAIY8BQADIAQAhnwEBAMUBACGgAQgA1AEAIaEBAQDFAQAhogEBAMUBACGkAQAA1wGkASKlAUAAyAEAIQMAAAAZACACAACUAQAwIAAAlQEAIAMAAAAZACACAAAaADADAAAbACABAAAADwAgAQAAAA8AIAMAAAANACACAAAOADADAAAPACADAAAADQAgAgAADgAwAwAADwAgAwAAAA0AIAIAAA4AMAMAAA8AIAgKAACYAgAgCwAAmQIAIIoBAQAAAAGNAQEAAAABmwEBAAAAAZwBAQAAAAGdAQgAAAABngECAAAAAQEUAACdAQAgBooBAQAAAAGNAQEAAAABmwEBAAAAAZwBAQAAAAGdAQgAAAABngECAAAAAQEUAACfAQAwARQAAJ8BADAICgAAlgIAIAsAAJcCACCKAQEAiAIAIY0BAQCIAgAhmwEBAIgCACGcAQEAiAIAIZ0BCACVAgAhngECAIkCACECAAAADwAgFAAAogEAIAaKAQEAiAIAIY0BAQCIAgAhmwEBAIgCACGcAQEAiAIAIZ0BCACVAgAhngECAIkCACECAAAADQAgFAAApAEAIAIAAAANACAUAACkAQAgAwAAAA8AIBsAAJ0BACAcAACiAQAgAQAAAA8AIAEAAAANACAFBgAAkAIAICEAAJMCACAiAACSAgAgUwAAkQIAIFQAAJQCACAJhwEAANMBADCIAQAAqwEAEIkBAADTAQAwigEBAMUBACGNAQEAxQEAIZsBAQDFAQAhnAEBAMUBACGdAQgA1AEAIZ4BAgDGAQAhAwAAAA0AIAIAAKoBADAgAACrAQAgAwAAAA0AIAIAAA4AMAMAAA8AIAEAAAAVACABAAAAFQAgAwAAABMAIAIAABQAMAMAABUAIAMAAAATACACAAAUADADAAAVACADAAAAEwAgAgAAFAAwAwAAFQAgCAgAAI8CACALAACOAgAgigEBAAAAAYsBAgAAAAGMAQEAAAABjQEBAAAAAY4BAQAAAAGPAUAAAAABARQAALMBACAGigEBAAAAAYsBAgAAAAGMAQEAAAABjQEBAAAAAY4BAQAAAAGPAUAAAAABARQAALUBADABFAAAtQEAMAgIAACNAgAgCwAAjAIAIIoBAQCIAgAhiwECAIkCACGMAQEAigIAIY0BAQCIAgAhjgEBAIgCACGPAUAAiwIAIQIAAAAVACAUAAC4AQAgBooBAQCIAgAhiwECAIkCACGMAQEAigIAIY0BAQCIAgAhjgEBAIgCACGPAUAAiwIAIQIAAAATACAUAAC6AQAgAgAAABMAIBQAALoBACADAAAAFQAgGwAAswEAIBwAALgBACABAAAAFQAgAQAAABMAIAYGAACDAgAgIQAAhgIAICIAAIUCACBTAACEAgAgVAAAhwIAIIwBAACCAgAgCYcBAADEAQAwiAEAAMEBABCJAQAAxAEAMIoBAQDFAQAhiwECAMYBACGMAQEAxwEAIY0BAQDFAQAhjgEBAMUBACGPAUAAyAEAIQMAAAATACACAADAAQAwIAAAwQEAIAMAAAATACACAAAUADADAAAVACAJhwEAAMQBADCIAQAAwQEAEIkBAADEAQAwigEBAMUBACGLAQIAxgEAIYwBAQDHAQAhjQEBAMUBACGOAQEAxQEAIY8BQADIAQAhDgYAAMoBACAhAADSAQAgIgAA0gEAIJABAQAAAAGRAQEAAAAEkgEBAAAABJMBAQAAAAGUAQEAAAABlQEBAAAAAZYBAQAAAAGXAQEA0QEAIZgBAQAAAAGZAQEAAAABmgEBAAAAAQ0GAADKAQAgIQAAygEAICIAAMoBACBTAADQAQAgVAAAygEAIJABAgAAAAGRAQIAAAAEkgECAAAABJMBAgAAAAGUAQIAAAABlQECAAAAAZYBAgAAAAGXAQIAzwEAIQ4GAADNAQAgIQAAzgEAICIAAM4BACCQAQEAAAABkQEBAAAABZIBAQAAAAWTAQEAAAABlAEBAAAAAZUBAQAAAAGWAQEAAAABlwEBAMwBACGYAQEAAAABmQEBAAAAAZoBAQAAAAELBgAAygEAICEAAMsBACAiAADLAQAgkAFAAAAAAZEBQAAAAASSAUAAAAAEkwFAAAAAAZQBQAAAAAGVAUAAAAABlgFAAAAAAZcBQADJAQAhCwYAAMoBACAhAADLAQAgIgAAywEAIJABQAAAAAGRAUAAAAAEkgFAAAAABJMBQAAAAAGUAUAAAAABlQFAAAAAAZYBQAAAAAGXAUAAyQEAIQiQAQIAAAABkQECAAAABJIBAgAAAASTAQIAAAABlAECAAAAAZUBAgAAAAGWAQIAAAABlwECAMoBACEIkAFAAAAAAZEBQAAAAASSAUAAAAAEkwFAAAAAAZQBQAAAAAGVAUAAAAABlgFAAAAAAZcBQADLAQAhDgYAAM0BACAhAADOAQAgIgAAzgEAIJABAQAAAAGRAQEAAAAFkgEBAAAABZMBAQAAAAGUAQEAAAABlQEBAAAAAZYBAQAAAAGXAQEAzAEAIZgBAQAAAAGZAQEAAAABmgEBAAAAAQiQAQIAAAABkQECAAAABZIBAgAAAAWTAQIAAAABlAECAAAAAZUBAgAAAAGWAQIAAAABlwECAM0BACELkAEBAAAAAZEBAQAAAAWSAQEAAAAFkwEBAAAAAZQBAQAAAAGVAQEAAAABlgEBAAAAAZcBAQDOAQAhmAEBAAAAAZkBAQAAAAGaAQEAAAABDQYAAMoBACAhAADKAQAgIgAAygEAIFMAANABACBUAADKAQAgkAECAAAAAZEBAgAAAASSAQIAAAAEkwECAAAAAZQBAgAAAAGVAQIAAAABlgECAAAAAZcBAgDPAQAhCJABCAAAAAGRAQgAAAAEkgEIAAAABJMBCAAAAAGUAQgAAAABlQEIAAAAAZYBCAAAAAGXAQgA0AEAIQ4GAADKAQAgIQAA0gEAICIAANIBACCQAQEAAAABkQEBAAAABJIBAQAAAASTAQEAAAABlAEBAAAAAZUBAQAAAAGWAQEAAAABlwEBANEBACGYAQEAAAABmQEBAAAAAZoBAQAAAAELkAEBAAAAAZEBAQAAAASSAQEAAAAEkwEBAAAAAZQBAQAAAAGVAQEAAAABlgEBAAAAAZcBAQDSAQAhmAEBAAAAAZkBAQAAAAGaAQEAAAABCYcBAADTAQAwiAEAAKsBABCJAQAA0wEAMIoBAQDFAQAhjQEBAMUBACGbAQEAxQEAIZwBAQDFAQAhnQEIANQBACGeAQIAxgEAIQ0GAADKAQAgIQAA0AEAICIAANABACBTAADQAQAgVAAA0AEAIJABCAAAAAGRAQgAAAAEkgEIAAAABJMBCAAAAAGUAQgAAAABlQEIAAAAAZYBCAAAAAGXAQgA1QEAIQ0GAADKAQAgIQAA0AEAICIAANABACBTAADQAQAgVAAA0AEAIJABCAAAAAGRAQgAAAAEkgEIAAAABJMBCAAAAAGUAQgAAAABlQEIAAAAAZYBCAAAAAGXAQgA1QEAIQyHAQAA1gEAMIgBAACVAQAQiQEAANYBADCKAQEAxQEAIY4BAQDFAQAhjwFAAMgBACGfAQEAxQEAIaABCADUAQAhoQEBAMUBACGiAQEAxQEAIaQBAADXAaQBIqUBQADIAQAhBwYAAMoBACAhAADZAQAgIgAA2QEAIJABAAAApAECkQEAAACkAQiSAQAAAKQBCJcBAADYAaQBIgcGAADKAQAgIQAA2QEAICIAANkBACCQAQAAAKQBApEBAAAApAEIkgEAAACkAQiXAQAA2AGkASIEkAEAAACkAQKRAQAAAKQBCJIBAAAApAEIlwEAANkBpAEiDocBAADaAQAwiAEAAH8AEIkBAADaAQAwigEBAMUBACGPAUAAyAEAIZwBAQDFAQAhnQEIANQBACGfAQEAxQEAIaUBQADIAQAhpgEBAMcBACGnAQEAxwEAIagBAADbAQAgqQEgANwBACGqAQEAxwEAIQSQAQEAAAAFqwEBAAAAAawBAQAAAAStAQEAAAAEBQYAAMoBACAhAADeAQAgIgAA3gEAIJABIAAAAAGXASAA3QEAIQUGAADKAQAgIQAA3gEAICIAAN4BACCQASAAAAABlwEgAN0BACECkAEgAAAAAZcBIADeAQAhCIcBAADfAQAwiAEAAGcAEIkBAADfAQAwigEBAMUBACGPAUAAyAEAIZwBAQDFAQAhrgEBAMUBACGvASAA3AEAIQkFAADkAQAghwEAAOABADCIAQAACQAQiQEAAOABADCKAQEA4QEAIY8BQADjAQAhnAEBAOEBACGuAQEA4QEAIa8BIADiAQAhC5ABAQAAAAGRAQEAAAAEkgEBAAAABJMBAQAAAAGUAQEAAAABlQEBAAAAAZYBAQAAAAGXAQEA0gEAIZgBAQAAAAGZAQEAAAABmgEBAAAAAQKQASAAAAABlwEgAN4BACEIkAFAAAAAAZEBQAAAAASSAUAAAAAEkwFAAAAAAZQBQAAAAAGVAUAAAAABlgFAAAAAAZcBQADLAQAhA7ABAAAFACCxAQAABQAgsgEAAAUAIAqHAQAA5QEAMIgBAABPABCJAQAA5QEAMIoBAQDFAQAhjwFAAMgBACGzAQEAxQEAIbQBAADbAQAgtQEBAMUBACG2ASAA3AEAIbcBAQDFAQAhDQEAAOcBACAFAADkAQAgDgAA6AEAIIcBAADmAQAwiAEAAAMAEIkBAADmAQAwigEBAOEBACGPAUAA4wEAIbMBAQDhAQAhtAEAANsBACC1AQEA4QEAIbYBIADiAQAhtwEBAOEBACEQBAAA9AEAIA0AAPUBACAOAADoAQAghwEAAPABADCIAQAAJAAQiQEAAPABADCKAQEA4QEAIY8BQADjAQAhnAEBAPEBACGkAQAA8wG9ASKlAUAA4wEAIbgBAQDhAQAhuQEBAOEBACG7AQAA8gG7ASK9AQAAJAAgvgEAACQAIAOwAQAAGQAgsQEAABkAILIBAAAZACALhwEAAOkBADCIAQAANwAQiQEAAOkBADCKAQEAxQEAIY8BQADIAQAhnAEBAMcBACGkAQAA6wG9ASKlAUAAyAEAIbgBAQDFAQAhuQEBAMUBACG7AQAA6gG7ASIHBgAAygEAICEAAO8BACAiAADvAQAgkAEAAAC7AQKRAQAAALsBCJIBAAAAuwEIlwEAAO4BuwEiBwYAAMoBACAhAADtAQAgIgAA7QEAIJABAAAAvQECkQEAAAC9AQiSAQAAAL0BCJcBAADsAb0BIgcGAADKAQAgIQAA7QEAICIAAO0BACCQAQAAAL0BApEBAAAAvQEIkgEAAAC9AQiXAQAA7AG9ASIEkAEAAAC9AQKRAQAAAL0BCJIBAAAAvQEIlwEAAO0BvQEiBwYAAMoBACAhAADvAQAgIgAA7wEAIJABAAAAuwECkQEAAAC7AQiSAQAAALsBCJcBAADuAbsBIgSQAQAAALsBApEBAAAAuwEIkgEAAAC7AQiXAQAA7wG7ASIOBAAA9AEAIA0AAPUBACAOAADoAQAghwEAAPABADCIAQAAJAAQiQEAAPABADCKAQEA4QEAIY8BQADjAQAhnAEBAPEBACGkAQAA8wG9ASKlAUAA4wEAIbgBAQDhAQAhuQEBAOEBACG7AQAA8gG7ASILkAEBAAAAAZEBAQAAAAWSAQEAAAAFkwEBAAAAAZQBAQAAAAGVAQEAAAABlgEBAAAAAZcBAQDOAQAhmAEBAAAAAZkBAQAAAAGaAQEAAAABBJABAAAAuwECkQEAAAC7AQiSAQAAALsBCJcBAADvAbsBIgSQAQAAAL0BApEBAAAAvQEIkgEAAAC9AQiXAQAA7QG9ASIPAQAA5wEAIAUAAOQBACAOAADoAQAghwEAAOYBADCIAQAAAwAQiQEAAOYBADCKAQEA4QEAIY8BQADjAQAhswEBAOEBACG0AQAA2wEAILUBAQDhAQAhtgEgAOIBACG3AQEA4QEAIb0BAAADACC-AQAAAwAgA7ABAAATACCxAQAAEwAgsgEAABMAIA8EAAD5AQAgCAAA5wEAIAkAAPoBACCHAQAA9gEAMIgBAAAZABCJAQAA9gEAMIoBAQDhAQAhjgEBAOEBACGPAUAA4wEAIZ8BAQDhAQAhoAEIAPcBACGhAQEA4QEAIaIBAQDhAQAhpAEAAPgBpAEipQFAAOMBACEIkAEIAAAAAZEBCAAAAASSAQgAAAAEkwEIAAAAAZQBCAAAAAGVAQgAAAABlgEIAAAAAZcBCADQAQAhBJABAAAApAECkQEAAACkAQiSAQAAAKQBCJcBAADZAaQBIg8BAADnAQAgBQAA5AEAIA4AAOgBACCHAQAA5gEAMIgBAAADABCJAQAA5gEAMIoBAQDhAQAhjwFAAOMBACGzAQEA4QEAIbQBAADbAQAgtQEBAOEBACG2ASAA4gEAIbcBAQDhAQAhvQEAAAMAIL4BAAADACADsAEAAA0AILEBAAANACCyAQAADQAgCwgAAOcBACALAAD9AQAghwEAAPsBADCIAQAAEwAQiQEAAPsBADCKAQEA4QEAIYsBAgD8AQAhjAEBAPEBACGNAQEA4QEAIY4BAQDhAQAhjwFAAOMBACEIkAECAAAAAZEBAgAAAASSAQIAAAAEkwECAAAAAZQBAgAAAAGVAQIAAAABlgECAAAAAZcBAgDKAQAhFAQAAPkBACAHAACBAgAgDAAA-gEAIA0AAPUBACCHAQAAgAIAMIgBAAAFABCJAQAAgAIAMIoBAQDhAQAhjwFAAOMBACGcAQEA4QEAIZ0BCAD3AQAhnwEBAOEBACGlAUAA4wEAIaYBAQDxAQAhpwEBAPEBACGoAQAA2wEAIKkBIADiAQAhqgEBAPEBACG9AQAABQAgvgEAAAUAIAsKAAD_AQAgCwAA_QEAIIcBAAD-AQAwiAEAAA0AEIkBAAD-AQAwigEBAOEBACGNAQEA4QEAIZsBAQDhAQAhnAEBAOEBACGdAQgA9wEAIZ4BAgD8AQAhEQQAAPkBACAIAADnAQAgCQAA-gEAIIcBAAD2AQAwiAEAABkAEIkBAAD2AQAwigEBAOEBACGOAQEA4QEAIY8BQADjAQAhnwEBAOEBACGgAQgA9wEAIaEBAQDhAQAhogEBAOEBACGkAQAA-AGkASKlAUAA4wEAIb0BAAAZACC-AQAAGQAgEgQAAPkBACAHAACBAgAgDAAA-gEAIA0AAPUBACCHAQAAgAIAMIgBAAAFABCJAQAAgAIAMIoBAQDhAQAhjwFAAOMBACGcAQEA4QEAIZ0BCAD3AQAhnwEBAOEBACGlAUAA4wEAIaYBAQDxAQAhpwEBAPEBACGoAQAA2wEAIKkBIADiAQAhqgEBAPEBACELBQAA5AEAIIcBAADgAQAwiAEAAAkAEIkBAADgAQAwigEBAOEBACGPAUAA4wEAIZwBAQDhAQAhrgEBAOEBACGvASAA4gEAIb0BAAAJACC-AQAACQAgAAAAAAAAAcIBAQAAAAEFwgECAAAAAckBAgAAAAHKAQIAAAABywECAAAAAcwBAgAAAAEBwgEBAAAAAQHCAUAAAAABBRsAAOADACAcAADmAwAgvwEAAOEDACDAAQAA5QMAIMUBAAAHACAFGwAA3gMAIBwAAOMDACC_AQAA3wMAIMABAADiAwAgxQEAAAEAIAMbAADgAwAgvwEAAOEDACDFAQAABwAgAxsAAN4DACC_AQAA3wMAIMUBAAABACAAAAAAAAXCAQgAAAAByQEIAAAAAcoBCAAAAAHLAQgAAAABzAEIAAAAAQUbAADWAwAgHAAA3AMAIL8BAADXAwAgwAEAANsDACDFAQAAGwAgBRsAANQDACAcAADZAwAgvwEAANUDACDAAQAA2AMAIMUBAAAHACADGwAA1gMAIL8BAADXAwAgxQEAABsAIAMbAADUAwAgvwEAANUDACDFAQAABwAgAAAAAAABwgEAAACkAQIFGwAAywMAIBwAANIDACC_AQAAzAMAIMABAADRAwAgxQEAAAEAIAUbAADJAwAgHAAAzwMAIL8BAADKAwAgwAEAAM4DACDFAQAAOgAgCxsAAKMCADAcAACoAgAwvwEAAKQCADDAAQAApQIAMMEBAACmAgAgwgEAAKcCADDDAQAApwIAMMQBAACnAgAwxQEAAKcCADDGAQAAqQIAMMcBAACqAgAwBgsAAJkCACCKAQEAAAABjQEBAAAAAZwBAQAAAAGdAQgAAAABngECAAAAAQIAAAAPACAbAACuAgAgAwAAAA8AIBsAAK4CACAcAACtAgAgARQAAM0DADALCgAA_wEAIAsAAP0BACCHAQAA_gEAMIgBAAANABCJAQAA_gEAMIoBAQAAAAGNAQEA4QEAIZsBAQDhAQAhnAEBAOEBACGdAQgA9wEAIZ4BAgD8AQAhAgAAAA8AIBQAAK0CACACAAAAqwIAIBQAAKwCACAJhwEAAKoCADCIAQAAqwIAEIkBAACqAgAwigEBAOEBACGNAQEA4QEAIZsBAQDhAQAhnAEBAOEBACGdAQgA9wEAIZ4BAgD8AQAhCYcBAACqAgAwiAEAAKsCABCJAQAAqgIAMIoBAQDhAQAhjQEBAOEBACGbAQEA4QEAIZwBAQDhAQAhnQEIAPcBACGeAQIA_AEAIQWKAQEAiAIAIY0BAQCIAgAhnAEBAIgCACGdAQgAlQIAIZ4BAgCJAgAhBgsAAJcCACCKAQEAiAIAIY0BAQCIAgAhnAEBAIgCACGdAQgAlQIAIZ4BAgCJAgAhBgsAAJkCACCKAQEAAAABjQEBAAAAAZwBAQAAAAGdAQgAAAABngECAAAAAQMbAADLAwAgvwEAAMwDACDFAQAAAQAgAxsAAMkDACC_AQAAygMAIMUBAAA6ACAEGwAAowIAML8BAACkAgAwwQEAAKYCACDFAQAApwIAMAAAAAAAAsIBAQAAAATIAQEAAAAFAcIBIAAAAAEFGwAAvwMAIBwAAMcDACC_AQAAwAMAIMABAADGAwAgxQEAADoAIAcbAAC9AwAgHAAAxAMAIL8BAAC-AwAgwAEAAMMDACDDAQAACQAgxAEAAAkAIMUBAABSACALGwAAyQIAMBwAAM0CADC_AQAAygIAMMABAADLAgAwwQEAAMwCACDCAQAApwIAMMMBAACnAgAwxAEAAKcCADDFAQAApwIAMMYBAADOAgAwxwEAAKoCADALGwAAvQIAMBwAAMICADC_AQAAvgIAMMABAAC_AgAwwQEAAMACACDCAQAAwQIAMMMBAADBAgAwxAEAAMECADDFAQAAwQIAMMYBAADDAgAwxwEAAMQCADAGCAAAjwIAIIoBAQAAAAGLAQIAAAABjAEBAAAAAY4BAQAAAAGPAUAAAAABAgAAABUAIBsAAMgCACADAAAAFQAgGwAAyAIAIBwAAMcCACABFAAAwgMAMAsIAADnAQAgCwAA_QEAIIcBAAD7AQAwiAEAABMAEIkBAAD7AQAwigEBAAAAAYsBAgD8AQAhjAEBAPEBACGNAQEA4QEAIY4BAQDhAQAhjwFAAOMBACECAAAAFQAgFAAAxwIAIAIAAADFAgAgFAAAxgIAIAmHAQAAxAIAMIgBAADFAgAQiQEAAMQCADCKAQEA4QEAIYsBAgD8AQAhjAEBAPEBACGNAQEA4QEAIY4BAQDhAQAhjwFAAOMBACEJhwEAAMQCADCIAQAAxQIAEIkBAADEAgAwigEBAOEBACGLAQIA_AEAIYwBAQDxAQAhjQEBAOEBACGOAQEA4QEAIY8BQADjAQAhBYoBAQCIAgAhiwECAIkCACGMAQEAigIAIY4BAQCIAgAhjwFAAIsCACEGCAAAjQIAIIoBAQCIAgAhiwECAIkCACGMAQEAigIAIY4BAQCIAgAhjwFAAIsCACEGCAAAjwIAIIoBAQAAAAGLAQIAAAABjAEBAAAAAY4BAQAAAAGPAUAAAAABBgoAAJgCACCKAQEAAAABmwEBAAAAAZwBAQAAAAGdAQgAAAABngECAAAAAQIAAAAPACAbAADRAgAgAwAAAA8AIBsAANECACAcAADQAgAgARQAAMEDADACAAAADwAgFAAA0AIAIAIAAACrAgAgFAAAzwIAIAWKAQEAiAIAIZsBAQCIAgAhnAEBAIgCACGdAQgAlQIAIZ4BAgCJAgAhBgoAAJYCACCKAQEAiAIAIZsBAQCIAgAhnAEBAIgCACGdAQgAlQIAIZ4BAgCJAgAhBgoAAJgCACCKAQEAAAABmwEBAAAAAZwBAQAAAAGdAQgAAAABngECAAAAAQHCAQEAAAAEAxsAAL8DACC_AQAAwAMAIMUBAAA6ACADGwAAvQMAIL8BAAC-AwAgxQEAAFIAIAQbAADJAgAwvwEAAMoCADDBAQAAzAIAIMUBAACnAgAwBBsAAL0CADC_AQAAvgIAMMEBAADAAgAgxQEAAMECADAAAAALGwAA2wIAMBwAAOACADC_AQAA3AIAMMABAADdAgAwwQEAAN4CACDCAQAA3wIAMMMBAADfAgAwxAEAAN8CADDFAQAA3wIAMMYBAADhAgAwxwEAAOICADANBAAA0wIAIAwAANUCACANAADWAgAgigEBAAAAAY8BQAAAAAGcAQEAAAABnQEIAAAAAZ8BAQAAAAGlAUAAAAABpgEBAAAAAacBAQAAAAGoAQAA0gIAIKkBIAAAAAECAAAABwAgGwAA5gIAIAMAAAAHACAbAADmAgAgHAAA5QIAIAEUAAC8AwAwEgQAAPkBACAHAACBAgAgDAAA-gEAIA0AAPUBACCHAQAAgAIAMIgBAAAFABCJAQAAgAIAMIoBAQAAAAGPAUAA4wEAIZwBAQDhAQAhnQEIAPcBACGfAQEA4QEAIaUBQADjAQAhpgEBAPEBACGnAQEA8QEAIagBAADbAQAgqQEgAOIBACGqAQEA8QEAIQIAAAAHACAUAADlAgAgAgAAAOMCACAUAADkAgAgDocBAADiAgAwiAEAAOMCABCJAQAA4gIAMIoBAQDhAQAhjwFAAOMBACGcAQEA4QEAIZ0BCAD3AQAhnwEBAOEBACGlAUAA4wEAIaYBAQDxAQAhpwEBAPEBACGoAQAA2wEAIKkBIADiAQAhqgEBAPEBACEOhwEAAOICADCIAQAA4wIAEIkBAADiAgAwigEBAOEBACGPAUAA4wEAIZwBAQDhAQAhnQEIAPcBACGfAQEA4QEAIaUBQADjAQAhpgEBAPEBACGnAQEA8QEAIagBAADbAQAgqQEgAOIBACGqAQEA8QEAIQqKAQEAiAIAIY8BQACLAgAhnAEBAIgCACGdAQgAlQIAIZ8BAQCIAgAhpQFAAIsCACGmAQEAigIAIacBAQCKAgAhqAEAALcCACCpASAAuAIAIQ0EAAC5AgAgDAAAuwIAIA0AALwCACCKAQEAiAIAIY8BQACLAgAhnAEBAIgCACGdAQgAlQIAIZ8BAQCIAgAhpQFAAIsCACGmAQEAigIAIacBAQCKAgAhqAEAALcCACCpASAAuAIAIQ0EAADTAgAgDAAA1QIAIA0AANYCACCKAQEAAAABjwFAAAAAAZwBAQAAAAGdAQgAAAABnwEBAAAAAaUBQAAAAAGmAQEAAAABpwEBAAAAAagBAADSAgAgqQEgAAAAAQQbAADbAgAwvwEAANwCADDBAQAA3gIAIMUBAADfAgAwAAAAAALCAQEAAAAEyAEBAAAABQUbAAC1AwAgHAAAugMAIL8BAAC2AwAgwAEAALkDACDFAQAAAQAgCxsAAPwCADAcAACAAwAwvwEAAP0CADDAAQAA_gIAMMEBAAD_AgAgwgEAAN8CADDDAQAA3wIAMMQBAADfAgAwxQEAAN8CADDGAQAAgQMAMMcBAADiAgAwCxsAAPACADAcAAD1AgAwvwEAAPECADDAAQAA8gIAMMEBAADzAgAgwgEAAPQCADDDAQAA9AIAMMQBAAD0AgAwxQEAAPQCADDGAQAA9gIAMMcBAAD3AgAwCggAAK8CACAJAACxAgAgigEBAAAAAY4BAQAAAAGPAUAAAAABoAEIAAAAAaEBAQAAAAGiAQEAAAABpAEAAACkAQKlAUAAAAABAgAAABsAIBsAAPsCACADAAAAGwAgGwAA-wIAIBwAAPoCACABFAAAuAMAMA8EAAD5AQAgCAAA5wEAIAkAAPoBACCHAQAA9gEAMIgBAAAZABCJAQAA9gEAMIoBAQAAAAGOAQEA4QEAIY8BQADjAQAhnwEBAOEBACGgAQgA9wEAIaEBAQDhAQAhogEBAOEBACGkAQAA-AGkASKlAUAA4wEAIQIAAAAbACAUAAD6AgAgAgAAAPgCACAUAAD5AgAgDIcBAAD3AgAwiAEAAPgCABCJAQAA9wIAMIoBAQDhAQAhjgEBAOEBACGPAUAA4wEAIZ8BAQDhAQAhoAEIAPcBACGhAQEA4QEAIaIBAQDhAQAhpAEAAPgBpAEipQFAAOMBACEMhwEAAPcCADCIAQAA-AIAEIkBAAD3AgAwigEBAOEBACGOAQEA4QEAIY8BQADjAQAhnwEBAOEBACGgAQgA9wEAIaEBAQDhAQAhogEBAOEBACGkAQAA-AGkASKlAUAA4wEAIQiKAQEAiAIAIY4BAQCIAgAhjwFAAIsCACGgAQgAlQIAIaEBAQCIAgAhogEBAIgCACGkAQAAnwKkASKlAUAAiwIAIQoIAACgAgAgCQAAogIAIIoBAQCIAgAhjgEBAIgCACGPAUAAiwIAIaABCACVAgAhoQEBAIgCACGiAQEAiAIAIaQBAACfAqQBIqUBQACLAgAhCggAAK8CACAJAACxAgAgigEBAAAAAY4BAQAAAAGPAUAAAAABoAEIAAAAAaEBAQAAAAGiAQEAAAABpAEAAACkAQKlAUAAAAABDQcAANQCACAMAADVAgAgDQAA1gIAIIoBAQAAAAGPAUAAAAABnAEBAAAAAZ0BCAAAAAGlAUAAAAABpgEBAAAAAacBAQAAAAGoAQAA0gIAIKkBIAAAAAGqAQEAAAABAgAAAAcAIBsAAIQDACADAAAABwAgGwAAhAMAIBwAAIMDACABFAAAtwMAMAIAAAAHACAUAACDAwAgAgAAAOMCACAUAACCAwAgCooBAQCIAgAhjwFAAIsCACGcAQEAiAIAIZ0BCACVAgAhpQFAAIsCACGmAQEAigIAIacBAQCKAgAhqAEAALcCACCpASAAuAIAIaoBAQCKAgAhDQcAALoCACAMAAC7AgAgDQAAvAIAIIoBAQCIAgAhjwFAAIsCACGcAQEAiAIAIZ0BCACVAgAhpQFAAIsCACGmAQEAigIAIacBAQCKAgAhqAEAALcCACCpASAAuAIAIaoBAQCKAgAhDQcAANQCACAMAADVAgAgDQAA1gIAIIoBAQAAAAGPAUAAAAABnAEBAAAAAZ0BCAAAAAGlAUAAAAABpgEBAAAAAacBAQAAAAGoAQAA0gIAIKkBIAAAAAGqAQEAAAABAcIBAQAAAAQDGwAAtQMAIL8BAAC2AwAgxQEAAAEAIAQbAAD8AgAwvwEAAP0CADDBAQAA_wIAIMUBAADfAgAwBBsAAPACADC_AQAA8QIAMMEBAADzAgAgxQEAAPQCADAEBAAArQMAIA0AAK4DACAOAACKAwAgnAEAAIICACAAAAAAAcIBAAAAuwECAcIBAAAAvQECBxsAAKUDACAcAACoAwAgvwEAAKYDACDAAQAApwMAIMMBAAADACDEAQAAAwAgxQEAADoAIAsbAACcAwAwHAAAoAMAML8BAACdAwAwwAEAAJ4DADDBAQAAnwMAIMIBAAD0AgAwwwEAAPQCADDEAQAA9AIAMMUBAAD0AgAwxgEAAKEDADDHAQAA9wIAMAsbAACTAwAwHAAAlwMAML8BAACUAwAwwAEAAJUDADDBAQAAlgMAIMIBAADBAgAwwwEAAMECADDEAQAAwQIAMMUBAADBAgAwxgEAAJgDADDHAQAAxAIAMAYLAACOAgAgigEBAAAAAYsBAgAAAAGMAQEAAAABjQEBAAAAAY8BQAAAAAECAAAAFQAgGwAAmwMAIAMAAAAVACAbAACbAwAgHAAAmgMAIAEUAAC0AwAwAgAAABUAIBQAAJoDACACAAAAxQIAIBQAAJkDACAFigEBAIgCACGLAQIAiQIAIYwBAQCKAgAhjQEBAIgCACGPAUAAiwIAIQYLAACMAgAgigEBAIgCACGLAQIAiQIAIYwBAQCKAgAhjQEBAIgCACGPAUAAiwIAIQYLAACOAgAgigEBAAAAAYsBAgAAAAGMAQEAAAABjQEBAAAAAY8BQAAAAAEKBAAAsAIAIAkAALECACCKAQEAAAABjwFAAAAAAZ8BAQAAAAGgAQgAAAABoQEBAAAAAaIBAQAAAAGkAQAAAKQBAqUBQAAAAAECAAAAGwAgGwAApAMAIAMAAAAbACAbAACkAwAgHAAAowMAIAEUAACzAwAwAgAAABsAIBQAAKMDACACAAAA-AIAIBQAAKIDACAIigEBAIgCACGPAUAAiwIAIZ8BAQCIAgAhoAEIAJUCACGhAQEAiAIAIaIBAQCIAgAhpAEAAJ8CpAEipQFAAIsCACEKBAAAoQIAIAkAAKICACCKAQEAiAIAIY8BQACLAgAhnwEBAIgCACGgAQgAlQIAIaEBAQCIAgAhogEBAIgCACGkAQAAnwKkASKlAUAAiwIAIQoEAACwAgAgCQAAsQIAIIoBAQAAAAGPAUAAAAABnwEBAAAAAaABCAAAAAGhAQEAAAABogEBAAAAAaQBAAAApAECpQFAAAAAAQgFAACHAwAgDgAAiAMAIIoBAQAAAAGPAUAAAAABswEBAAAAAbQBAACFAwAgtQEBAAAAAbYBIAAAAAECAAAAOgAgGwAApQMAIAMAAAADACAbAAClAwAgHAAAqQMAIAoAAAADACAFAADuAgAgDgAA7wIAIBQAAKkDACCKAQEAiAIAIY8BQACLAgAhswEBAIgCACG0AQAA7AIAILUBAQCIAgAhtgEgALgCACEIBQAA7gIAIA4AAO8CACCKAQEAiAIAIY8BQACLAgAhswEBAIgCACG0AQAA7AIAILUBAQCIAgAhtgEgALgCACEDGwAApQMAIL8BAACmAwAgxQEAADoAIAQbAACcAwAwvwEAAJ0DADDBAQAAnwMAIMUBAAD0AgAwBBsAAJMDADC_AQAAlAMAMMEBAACWAwAgxQEAAMECADADAQAAiQMAIAUAAOgCACAOAACKAwAgAAAHBAAArQMAIAcAALIDACAMAACvAwAgDQAArgMAIKYBAACCAgAgpwEAAIICACCqAQAAggIAIAMEAACtAwAgCAAAiQMAIAkAAK8DACABBQAA6AIAIAiKAQEAAAABjwFAAAAAAZ8BAQAAAAGgAQgAAAABoQEBAAAAAaIBAQAAAAGkAQAAAKQBAqUBQAAAAAEFigEBAAAAAYsBAgAAAAGMAQEAAAABjQEBAAAAAY8BQAAAAAEKDQAArAMAIA4AAKsDACCKAQEAAAABjwFAAAAAAZwBAQAAAAGkAQAAAL0BAqUBQAAAAAG4AQEAAAABuQEBAAAAAbsBAAAAuwECAgAAAAEAIBsAALUDACAKigEBAAAAAY8BQAAAAAGcAQEAAAABnQEIAAAAAaUBQAAAAAGmAQEAAAABpwEBAAAAAagBAADSAgAgqQEgAAAAAaoBAQAAAAEIigEBAAAAAY4BAQAAAAGPAUAAAAABoAEIAAAAAaEBAQAAAAGiAQEAAAABpAEAAACkAQKlAUAAAAABAwAAACQAIBsAALUDACAcAAC7AwAgDAAAACQAIA0AAJIDACAOAACRAwAgFAAAuwMAIIoBAQCIAgAhjwFAAIsCACGcAQEAigIAIaQBAACPA70BIqUBQACLAgAhuAEBAIgCACG5AQEAiAIAIbsBAACOA7sBIgoNAACSAwAgDgAAkQMAIIoBAQCIAgAhjwFAAIsCACGcAQEAigIAIaQBAACPA70BIqUBQACLAgAhuAEBAIgCACG5AQEAiAIAIbsBAACOA7sBIgqKAQEAAAABjwFAAAAAAZwBAQAAAAGdAQgAAAABnwEBAAAAAaUBQAAAAAGmAQEAAAABpwEBAAAAAagBAADSAgAgqQEgAAAAAQWKAQEAAAABjwFAAAAAAZwBAQAAAAGuAQEAAAABrwEgAAAAAQIAAABSACAbAAC9AwAgCQEAAIYDACAOAACIAwAgigEBAAAAAY8BQAAAAAGzAQEAAAABtAEAAIUDACC1AQEAAAABtgEgAAAAAbcBAQAAAAECAAAAOgAgGwAAvwMAIAWKAQEAAAABmwEBAAAAAZwBAQAAAAGdAQgAAAABngECAAAAAQWKAQEAAAABiwECAAAAAYwBAQAAAAGOAQEAAAABjwFAAAAAAQMAAAAJACAbAAC9AwAgHAAAxQMAIAcAAAAJACAUAADFAwAgigEBAIgCACGPAUAAiwIAIZwBAQCIAgAhrgEBAIgCACGvASAAuAIAIQWKAQEAiAIAIY8BQACLAgAhnAEBAIgCACGuAQEAiAIAIa8BIAC4AgAhAwAAAAMAIBsAAL8DACAcAADIAwAgCwAAAAMAIAEAAO0CACAOAADvAgAgFAAAyAMAIIoBAQCIAgAhjwFAAIsCACGzAQEAiAIAIbQBAADsAgAgtQEBAIgCACG2ASAAuAIAIbcBAQCIAgAhCQEAAO0CACAOAADvAgAgigEBAIgCACGPAUAAiwIAIbMBAQCIAgAhtAEAAOwCACC1AQEAiAIAIbYBIAC4AgAhtwEBAIgCACEJAQAAhgMAIAUAAIcDACCKAQEAAAABjwFAAAAAAbMBAQAAAAG0AQAAhQMAILUBAQAAAAG2ASAAAAABtwEBAAAAAQIAAAA6ACAbAADJAwAgCgQAAKoDACANAACsAwAgigEBAAAAAY8BQAAAAAGcAQEAAAABpAEAAAC9AQKlAUAAAAABuAEBAAAAAbkBAQAAAAG7AQAAALsBAgIAAAABACAbAADLAwAgBYoBAQAAAAGNAQEAAAABnAEBAAAAAZ0BCAAAAAGeAQIAAAABAwAAAAMAIBsAAMkDACAcAADQAwAgCwAAAAMAIAEAAO0CACAFAADuAgAgFAAA0AMAIIoBAQCIAgAhjwFAAIsCACGzAQEAiAIAIbQBAADsAgAgtQEBAIgCACG2ASAAuAIAIbcBAQCIAgAhCQEAAO0CACAFAADuAgAgigEBAIgCACGPAUAAiwIAIbMBAQCIAgAhtAEAAOwCACC1AQEAiAIAIbYBIAC4AgAhtwEBAIgCACEDAAAAJAAgGwAAywMAIBwAANMDACAMAAAAJAAgBAAAkAMAIA0AAJIDACAUAADTAwAgigEBAIgCACGPAUAAiwIAIZwBAQCKAgAhpAEAAI8DvQEipQFAAIsCACG4AQEAiAIAIbkBAQCIAgAhuwEAAI4DuwEiCgQAAJADACANAACSAwAgigEBAIgCACGPAUAAiwIAIZwBAQCKAgAhpAEAAI8DvQEipQFAAIsCACG4AQEAiAIAIbkBAQCIAgAhuwEAAI4DuwEiDgQAANMCACAHAADUAgAgDQAA1gIAIIoBAQAAAAGPAUAAAAABnAEBAAAAAZ0BCAAAAAGfAQEAAAABpQFAAAAAAaYBAQAAAAGnAQEAAAABqAEAANICACCpASAAAAABqgEBAAAAAQIAAAAHACAbAADUAwAgCwQAALACACAIAACvAgAgigEBAAAAAY4BAQAAAAGPAUAAAAABnwEBAAAAAaABCAAAAAGhAQEAAAABogEBAAAAAaQBAAAApAECpQFAAAAAAQIAAAAbACAbAADWAwAgAwAAAAUAIBsAANQDACAcAADaAwAgEAAAAAUAIAQAALkCACAHAAC6AgAgDQAAvAIAIBQAANoDACCKAQEAiAIAIY8BQACLAgAhnAEBAIgCACGdAQgAlQIAIZ8BAQCIAgAhpQFAAIsCACGmAQEAigIAIacBAQCKAgAhqAEAALcCACCpASAAuAIAIaoBAQCKAgAhDgQAALkCACAHAAC6AgAgDQAAvAIAIIoBAQCIAgAhjwFAAIsCACGcAQEAiAIAIZ0BCACVAgAhnwEBAIgCACGlAUAAiwIAIaYBAQCKAgAhpwEBAIoCACGoAQAAtwIAIKkBIAC4AgAhqgEBAIoCACEDAAAAGQAgGwAA1gMAIBwAAN0DACANAAAAGQAgBAAAoQIAIAgAAKACACAUAADdAwAgigEBAIgCACGOAQEAiAIAIY8BQACLAgAhnwEBAIgCACGgAQgAlQIAIaEBAQCIAgAhogEBAIgCACGkAQAAnwKkASKlAUAAiwIAIQsEAAChAgAgCAAAoAIAIIoBAQCIAgAhjgEBAIgCACGPAUAAiwIAIZ8BAQCIAgAhoAEIAJUCACGhAQEAiAIAIaIBAQCIAgAhpAEAAJ8CpAEipQFAAIsCACEKBAAAqgMAIA4AAKsDACCKAQEAAAABjwFAAAAAAZwBAQAAAAGkAQAAAL0BAqUBQAAAAAG4AQEAAAABuQEBAAAAAbsBAAAAuwECAgAAAAEAIBsAAN4DACAOBAAA0wIAIAcAANQCACAMAADVAgAgigEBAAAAAY8BQAAAAAGcAQEAAAABnQEIAAAAAZ8BAQAAAAGlAUAAAAABpgEBAAAAAacBAQAAAAGoAQAA0gIAIKkBIAAAAAGqAQEAAAABAgAAAAcAIBsAAOADACADAAAAJAAgGwAA3gMAIBwAAOQDACAMAAAAJAAgBAAAkAMAIA4AAJEDACAUAADkAwAgigEBAIgCACGPAUAAiwIAIZwBAQCKAgAhpAEAAI8DvQEipQFAAIsCACG4AQEAiAIAIbkBAQCIAgAhuwEAAI4DuwEiCgQAAJADACAOAACRAwAgigEBAIgCACGPAUAAiwIAIZwBAQCKAgAhpAEAAI8DvQEipQFAAIsCACG4AQEAiAIAIbkBAQCIAgAhuwEAAI4DuwEiAwAAAAUAIBsAAOADACAcAADnAwAgEAAAAAUAIAQAALkCACAHAAC6AgAgDAAAuwIAIBQAAOcDACCKAQEAiAIAIY8BQACLAgAhnAEBAIgCACGdAQgAlQIAIZ8BAQCIAgAhpQFAAIsCACGmAQEAigIAIacBAQCKAgAhqAEAALcCACCpASAAuAIAIaoBAQCKAgAhDgQAALkCACAHAAC6AgAgDAAAuwIAIIoBAQCIAgAhjwFAAIsCACGcAQEAiAIAIZ0BCACVAgAhnwEBAIgCACGlAUAAiwIAIaYBAQCKAgAhpwEBAIoCACGoAQAAtwIAIKkBIAC4AgAhqgEBAIoCACEEBAQCBgAMDSAJDh8HBAEAAQUIAwYACw4cBwUEAAIGAAoHCgQMEAYNFgkCBQsDBgAFAQUMAAIKAAcLAAMEBAACBgAICAABCREGAQkSAAIIAAELAAMCDBcADRgAAgUdAA4eAAINIgAOIQAAAAADBgARIQASIgATAAAAAwYAESEAEiIAEwEBAAEBAQABAwYAGCEAGSIAGgAAAAMGABghABkiABoAAAMGAB8hACAiACEAAAADBgAfIQAgIgAhAgQAAgd0BAIEAAIHegQFBgAmIQApIgAqUwAnVAAoAAAAAAAFBgAmIQApIgAqUwAnVAAoAgQAAggAAQIEAAIIAAEFBgAvIQAyIgAzUwAwVAAxAAAAAAAFBgAvIQAyIgAzUwAwVAAxAgoABwsAAwIKAAcLAAMFBgA4IQA7IgA8UwA5VAA6AAAAAAAFBgA4IQA7IgA8UwA5VAA6AggAAQsAAwIIAAELAAMFBgBBIQBEIgBFUwBCVABDAAAAAAAFBgBBIQBEIgBFUwBCVABDDwIBECMBESYBEicBEygBFSoBFiwNFy0OGC8BGTENGjIPHTMBHjQBHzUNIzgQJDkUJTsCJjwCJz4CKD8CKUACKkICK0QNLEUVLUcCLkkNL0oWMEsCMUwCMk0NM1AXNFEbNVMENlQEN1YEOFcEOVgEOloEO1wNPF0cPV8EPmENP2IdQGMEQWQEQmUNQ2geRGkiRWoDRmsDR2wDSG0DSW4DSnADS3INTHMjTXYDTngNT3kkUHsDUXwDUn0NVYABJVaBAStXggEHWIMBB1mEAQdahQEHW4YBB1yIAQddigENXosBLF-NAQdgjwENYZABLWKRAQdjkgEHZJMBDWWWAS5mlwE0Z5gBBmiZAQZpmgEGapsBBmucAQZsngEGbaABDW6hATVvowEGcKUBDXGmATZypwEGc6gBBnSpAQ11rAE3dq0BPXeuAQl4rwEJebABCXqxAQl7sgEJfLQBCX22AQ1-twE-f7kBCYABuwENgQG8AT-CAb0BCYMBvgEJhAG_AQ2FAcIBQIYBwwFG"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.js"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.js");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var Role = {
  CUSTOMER: "CUSTOMER",
  PROVIDER: "PROVIDER",
  ADMIN: "ADMIN"
};
var UserStatus = {
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED"
};

// generated/prisma/client.ts
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/User/user.service.ts
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
var secret = "lsdngkdsbfgbkdf";
var createUser = async (Payload) => {
  const hashedPassword = await bcrypt.hash(Payload.password, 8);
  const result = await prisma.user.create({
    data: { ...Payload, password: hashedPassword }
  });
  const { password, ...newResult } = result;
  return newResult;
};
var loginUser = async (payload) => {
  const user = await prisma.user.findUnique({
    where: {
      email: payload.email
    }
  });
  if (!user) {
    throw new Error("User not found!");
  }
  const ispasswordMatched = await bcrypt.compare(
    payload.password,
    user.password
  );
  if (!ispasswordMatched) {
    throw new Error("Invalid credentials!!");
  }
  const userData = {
    id: user.id,
    name: user.name,
    role: user.role,
    status: user.status,
    email: user.email
  };
  const token = jwt.sign(userData, secret, { expiresIn: "4d" });
  return { user, token };
};
var getMyProfile = async (email) => {
  const user = await prisma.user.findUnique({
    where: { email },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true
    }
  });
  if (!user) {
    throw new Error("User not found");
  }
  return user;
};
var getAllUser = async () => {
  const result = await prisma.user.findMany();
  return result;
};
var updateUserRoleAndStatus = async (userId, payload) => {
  const user = await prisma.user.findUnique({
    where: { id: userId }
  });
  if (!user) {
    throw new Error("User not found");
  }
  return prisma.user.update({
    where: { id: userId },
    data: {
      ...payload.role && { role: payload.role },
      ...payload.status && { status: payload.status }
    },
    select: {
      id: true,
      email: true,
      role: true,
      status: true
    }
  });
};
var UserService = {
  createUser,
  getMyProfile,
  getAllUser,
  loginUser,
  updateUserRoleAndStatus
};

// src/utils/sendResponse.ts
var sendResponse = (res, data) => {
  const { statusCode, success, message, data: DataReponse } = data;
  res.status(statusCode).json({
    success,
    message,
    data: DataReponse
  });
};
var sendResponse_default = sendResponse;

// src/modules/User/user.controller.ts
var register = async (req, res, next) => {
  try {
    const result = await UserService.createUser(req.body);
    sendResponse_default(res, {
      statusCode: 201,
      success: true,
      message: "User created successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var loginUser2 = async (req, res) => {
  try {
    const result = await UserService.loginUser(req.body);
    res.cookie("token", result.token, {
      secure: false,
      httpOnly: true,
      sameSite: "strict"
      // none / strict / lax
    });
    sendResponse_default(res, {
      statusCode: 201,
      success: true,
      message: "User logged in successfully",
      data: result
    });
  } catch (error) {
    sendResponse_default(res, {
      statusCode: 500,
      success: false,
      message: error?.message || "Something went wrong",
      data: null
    });
  }
};
var getMyProfile2 = async (req, res) => {
  try {
    const email = req.user.email;
    const result = await UserService.getMyProfile(email);
    res.status(200).json({
      success: true,
      message: "Profile fetched successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message
    });
  }
};
var getallUser = async (req, res, next) => {
  try {
    const result = await UserService.getAllUser();
    sendResponse_default(res, {
      statusCode: 201,
      success: true,
      message: "User created successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var updateUserRoleAndStatus2 = async (req, res) => {
  try {
    const { id } = req.params;
    const { role, status } = req.body;
    if (role && !Object.values(Role).includes(role)) {
      return res.status(400).json({
        success: false,
        message: "Invalid role"
      });
    }
    if (status && !Object.values(UserStatus).includes(status)) {
      return res.status(400).json({
        success: false,
        message: "Invalid status"
      });
    }
    if (!role && !status) {
      return res.status(400).json({
        success: false,
        message: "Nothing to update"
      });
    }
    const result = await UserService.updateUserRoleAndStatus(id, {
      role,
      status
    });
    res.status(200).json({
      success: true,
      message: "User updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message
    });
  }
};
var UserController = {
  register,
  getallUser,
  getMyProfile: getMyProfile2,
  loginUser: loginUser2,
  updateUserRoleAndStatus: updateUserRoleAndStatus2
};

// src/middlewares/auth.ts
import jwt2 from "jsonwebtoken";
var auth = (...roles) => {
  return async (req, res, next) => {
    try {
      const token = req.cookies?.token || req.headers.authorization?.split(" ")[1];
      if (!token) {
        throw new Error("Token not found!!");
      }
      const decoded = jwt2.verify(token, secret);
      const userData = await prisma.user.findUnique({
        where: {
          email: decoded.email
        }
      });
      if (!userData) {
        throw new Error("Unauthorized!");
      }
      if (userData.status !== "ACTIVE") {
        throw new Error("Unauthorized!!");
      }
      if (roles.length && !roles.includes(decoded.role)) {
        throw new Error("Forbidden !!!");
      }
      req.user = decoded;
      next();
    } catch (error) {
      next(error);
    }
  };
};
var auth_default = auth;

// src/modules/User/user.route.ts
var userRouter = Router();
userRouter.post("/register", UserController.register);
userRouter.post("/login", UserController.loginUser);
userRouter.get("/me", auth_default(), UserController.getMyProfile);
userRouter.get("/allUser", UserController.getallUser);
userRouter.patch("/admin/:id", auth_default("ADMIN" /* admin */), UserController.updateUserRoleAndStatus);
var user_route_default = userRouter;

// src/modules/provider/provider.route.ts
import { Router as Router2 } from "express";

// src/modules/provider/provider.service.ts
var createProvider = async (payload) => {
  if (!payload.userId) {
    throw new Error("User ID is required to create provider");
  }
  const result = await prisma.provider.create({
    data: { ...payload }
  });
  return result;
};
var getAllProvider = async () => {
  const result = await prisma.provider.findMany({
    include: { user: true }
  });
  return result;
};
var providerService = {
  createProvider,
  getAllProvider
};

// src/modules/provider/provider.controller.ts
var createProvider2 = async (req, res, next) => {
  try {
    const payload = req.body;
    const userId = req.user?.id;
    const userRole = req.user?.role;
    const result = await providerService.createProvider({
      ...payload,
      userId
    });
    sendResponse_default(res, {
      statusCode: 201,
      success: true,
      message: "Provider created successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getAllProvider2 = async (req, res, next) => {
  try {
    const result = await providerService.getAllProvider();
    sendResponse_default(res, {
      statusCode: 201,
      success: true,
      message: "Provider get successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var providerController = {
  createProvider: createProvider2,
  getAllProvider: getAllProvider2
};

// src/modules/provider/provider.route.ts
var providerRoute = Router2();
providerRoute.post("/", auth_default("PROVIDER" /* provider */), providerController.createProvider);
providerRoute.get("/", providerController.getAllProvider);
var provider_route_default = providerRoute;

// src/modules/meal/meal.route.ts
import { Router as Router3 } from "express";

// src/modules/meal/meal.service.ts
var createMeal = async (payload) => {
  return prisma.meal.create({
    data: payload
  });
};
var getAllMeal = async (query) => {
  const { search, minPrice, maxPrice, categoryId, providerId } = query;
  return prisma.meal.findMany({
    where: {
      isAvailable: true,
      providerId: providerId || void 0,
      categoryId: categoryId || void 0,
      price: {
        gte: minPrice ? Number(minPrice) : void 0,
        lte: maxPrice ? Number(maxPrice) : void 0
      },
      name: search ? { contains: search, mode: "insensitive" } : void 0
    },
    include: {
      provider: true,
      category: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var getSingleMeal = (id) => {
  return prisma.meal.findUnique({
    where: { id },
    include: {
      provider: true,
      category: true,
      reviews: {
        include: {
          customer: {
            select: { id: true, name: true }
          }
        }
      }
    }
  });
};
var updateMeal = async (mealId, providerId, data) => {
  const meal = await prisma.meal.findFirst({
    where: { id: mealId, providerId }
  });
  if (!meal) {
    throw new Error("Meal not found or unauthorized");
  }
  return prisma.meal.update({
    where: { id: mealId },
    data
  });
};
var deleteMeal = async (mealId, providerId) => {
  const meal = await prisma.meal.findFirst({
    where: { id: mealId, providerId }
  });
  if (!meal) {
    throw new Error("Meal not found or unauthorized");
  }
  return prisma.meal.delete({
    where: { id: mealId }
  });
};
var mealService = {
  createMeal,
  getAllMeal,
  getSingleMeal,
  updateMeal,
  deleteMeal
};

// src/modules/meal/meal.controler.ts
var createMeal2 = async (req, res, next) => {
  try {
    const provider = await prisma.provider.findUnique({
      where: { userId: req.user?.id }
    });
    if (!provider) {
      throw new Error("Provider profile not found");
    }
    const result = await mealService.createMeal({
      ...req.body,
      providerId: provider.id
      // ✅ correct ID
    });
    res.status(201).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var getAllMeal2 = async (req, res) => {
  try {
    const result = await mealService.getAllMeal(req.query);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var getSingleMeal2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await mealService.getSingleMeal(id);
    if (!result) {
      return res.status(404).json({
        success: false,
        message: "Meal not found"
      });
    }
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var updateMeal2 = async (req, res) => {
  try {
    const { id } = req.params;
    const provider = await prisma.provider.findUnique({
      where: { userId: req.user?.id }
    });
    const providerId = provider?.id;
    const result = await mealService.updateMeal(
      id,
      providerId,
      req.body
    );
    res.status(200).json({
      success: true,
      message: "Meal updated successfully",
      data: result
    });
  } catch (error) {
    res.status(403).json({
      success: false,
      message: error.message
    });
  }
};
var deleteMeal2 = async (req, res) => {
  try {
    const { id } = req.params;
    const provider = await prisma.provider.findUnique({
      where: { userId: req.user?.id }
    });
    const providerId = provider?.id;
    const result = await mealService.deleteMeal(
      id,
      providerId
    );
    res.status(200).json({
      success: true,
      message: "Meal delete successfully"
    });
  } catch (error) {
    res.status(403).json({
      success: false,
      message: error.message
    });
  }
};
var mealController = {
  createMeal: createMeal2,
  getAllMeal: getAllMeal2,
  getSingleMeal: getSingleMeal2,
  updateMeal: updateMeal2,
  deleteMeal: deleteMeal2
};

// src/modules/meal/meal.route.ts
var mealRouter = Router3();
mealRouter.get("/", mealController.getAllMeal);
mealRouter.get("/:id", mealController.getSingleMeal);
mealRouter.post("/", auth_default("PROVIDER" /* provider */), mealController.createMeal);
mealRouter.patch("/:id", auth_default("PROVIDER" /* provider */), mealController.updateMeal);
mealRouter.delete("/:id", auth_default("PROVIDER" /* provider */), mealController.deleteMeal);
var meal_route_default = mealRouter;

// src/modules/order/order.route.ts
import { Router as Router4 } from "express";

// src/modules/order/order.service.ts
var OrderService = {
  // CREATE ORDER (Customer)
  createOrder: async (payload) => {
    const meals = await prisma.meal.findMany({
      where: {
        id: { in: payload.items.map((i) => i.mealId) }
      }
    });
    if (meals.length === 0) {
      throw new Error("Invalid meal items");
    }
    let totalAmount = 0;
    const orderItems = payload.items.map((item) => {
      const meal = meals.find((m) => m.id === item.mealId);
      if (!meal) {
        throw new Error("Meal not found");
      }
      totalAmount += meal.price * item.quantity;
      return {
        mealId: meal.id,
        name: meal.name,
        price: meal.price,
        quantity: item.quantity
      };
    });
    return prisma.order.create({
      data: {
        customerId: payload.customerId,
        providerId: payload.providerId,
        deliveryAddress: payload.deliveryAddress,
        totalAmount,
        items: {
          create: orderItems
        }
      },
      include: {
        items: true
      }
    });
  },
  getOrdersByAdmin: async () => {
    return prisma.order.findMany({
      orderBy: {
        createdAt: "desc"
      }
    });
  },
  // GET ORDERS FOR CUSTOMER
  getOrdersByCustomer: async (customerId) => {
    return prisma.order.findMany({
      where: { customerId },
      include: {
        items: true,
        provider: true
      },
      orderBy: {
        createdAt: "desc"
      }
    });
  },
  // GET ORDERS FOR PROVIDER service 
  getOrdersByProvider: async (providerId) => {
    return prisma.order.findMany({
      where: { providerId },
      include: {
        items: true,
        customer: {
          select: { id: true, name: true, email: true }
        }
      },
      orderBy: {
        createdAt: "desc"
      }
    });
  },
  // GET SINGLE ORDER (Customer / Provider / Admin)
  getOrderById: async (orderId) => {
    return prisma.order.findUnique({
      where: { id: orderId },
      include: {
        items: {
          include: { meal: true }
        },
        customer: true,
        provider: true
      }
    });
  },
  //   // UPDATE ORDER STATUS (Provider)
  updateOrderStatus: async (orderId, providerId, status) => {
    const order = await prisma.order.findFirst({
      where: { id: orderId, providerId }
    });
    if (!order) {
      throw new Error("Order not found or unauthorized");
    }
    return prisma.order.update({
      where: { id: orderId },
      data: { status }
    });
  },
  // provider states 
  // GET PROVIDER ORDER STATS
  getProviderStats: async (providerId) => {
    const totalOrders = await prisma.order.count({
      where: { providerId }
    });
    const pendingOrders = await prisma.order.count({
      where: { providerId, status: "PENDING" }
    });
    const deliveredOrders = await prisma.order.count({
      where: { providerId, status: "DELIVERED" }
    });
    const revenue = await prisma.order.aggregate({
      where: {
        providerId,
        status: "DELIVERED"
      },
      _sum: {
        totalAmount: true
      }
    });
    return {
      totalOrders,
      pendingOrders,
      deliveredOrders,
      totalRevenue: revenue._sum.totalAmount || 0
    };
  }
};

// src/modules/order/order.controller.ts
var OrderController = {
  // CREATE ORDER
  createOrder: async (req, res) => {
    try {
      const customerId = req.user.id;
      const result = await OrderService.createOrder({
        customerId,
        providerId: req.body.providerId,
        items: req.body.items,
        deliveryAddress: req.body.deliveryAddress
      });
      res.status(201).json({
        success: true,
        message: "Order placed successfully",
        data: result
      });
    } catch (error) {
      res.status(400).json({
        success: false,
        message: error.message
      });
    }
  },
  // GET MY ORDERS (Customer)
  getMyOrders: async (req, res) => {
    try {
      const customerId = req.user.id;
      const result = await OrderService.getOrdersByCustomer(customerId);
      res.status(200).json({
        success: true,
        data: result
      });
    } catch (error) {
      res.status(500).json({
        success: false,
        message: error.message
      });
    }
  },
  // GET PROVIDER ORDERS controller
  getProviderOrders: async (req, res) => {
    try {
      const userId = req.user.id;
      console.log(userId);
      const provider = await prisma.provider.findUnique({
        where: { userId }
      });
      if (!provider) {
        return res.status(404).json({
          success: false,
          message: "Provider not found"
        });
      }
      console.log(provider.id);
      const result = await OrderService.getOrdersByProvider(
        provider.id
      );
      res.status(200).json({
        success: true,
        data: result
      });
    } catch (error) {
      res.status(500).json({
        success: false,
        message: error.message
      });
    }
  },
  //get all order for admin
  getAdminOrders: async (req, res) => {
    try {
      const result = await OrderService.getOrdersByAdmin();
      res.status(200).json({
        success: true,
        data: result
      });
    } catch (error) {
      res.status(500).json({
        success: false,
        message: error.message
      });
    }
  },
  // GET ORDER DETAILS
  getOrderById: async (req, res) => {
    try {
      const order = await OrderService.getOrderById(req.params.id);
      if (!order) {
        return res.status(404).json({
          success: false,
          message: "Order not found"
        });
      }
      res.status(200).json({
        success: true,
        data: order
      });
    } catch (error) {
      res.status(500).json({
        success: false,
        message: error.message
      });
    }
  },
  // UPDATE ORDER STATUS (Provider)
  updateOrderStatus: async (req, res) => {
    try {
      const providerId = req.user.providerId;
      const { status } = req.body;
      const result = await OrderService.updateOrderStatus(
        req.params.id,
        providerId,
        status
      );
      res.status(200).json({
        success: true,
        message: "Order status updated",
        data: result
      });
    } catch (error) {
      res.status(403).json({
        success: false,
        message: error.message
      });
    }
  },
  // get provider states 
  getProviderStats: async (req, res) => {
    try {
      const userId = req.user.id;
      const provider = await prisma.provider.findFirst({
        where: { userId }
      });
      if (!provider) {
        return res.status(404).json({
          success: false,
          message: "Provider not found"
        });
      }
      const stats = await OrderService.getProviderStats(provider.id);
      res.status(200).json({
        success: true,
        data: stats
      });
    } catch (error) {
      res.status(500).json({
        success: false,
        message: error.message
      });
    }
  }
};

// src/modules/order/order.route.ts
var orderRouter = Router4();
orderRouter.post("/", auth_default("CUSTOMER" /* customer */), OrderController.createOrder);
orderRouter.get("/", auth_default("CUSTOMER" /* customer */, "ADMIN" /* admin */), OrderController.getMyOrders);
orderRouter.get("/admin", auth_default("ADMIN" /* admin */), OrderController.getAdminOrders);
orderRouter.get("/provider", auth_default("PROVIDER" /* provider */), OrderController.getProviderOrders);
orderRouter.get("/provider/stats", auth_default("PROVIDER" /* provider */), OrderController.getProviderStats);
orderRouter.get("/:id", auth_default(), OrderController.getOrderById);
orderRouter.patch("/:id", auth_default("PROVIDER" /* provider */), OrderController.updateOrderStatus);
var order_route_default = orderRouter;

// src/modules/review/review.route.ts
import express from "express";

// src/modules/review/review.service.ts
var createReview = async (payload, customerId) => {
  const meal = await prisma.meal.findUnique({
    where: { id: payload.mealId }
  });
  if (!meal) {
    throw new Error("Meal not found");
  }
  return prisma.review.create({
    data: {
      rating: payload.rating,
      comment: payload.comment,
      meal: {
        connect: { id: payload.mealId }
      },
      customer: {
        connect: { id: customerId }
      }
    }
  });
};
var getReviewsByMeal = async (mealId) => {
  return prisma.review.findMany({
    where: { mealId },
    include: {
      customer: {
        select: {
          id: true,
          name: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var updateReview = async (reviewId, customerId, payload) => {
  const review = await prisma.review.findUnique({
    where: { id: reviewId }
  });
  if (!review || review.customerId !== customerId) {
    throw new Error("Unauthorized or review not found");
  }
  return prisma.review.update({
    where: { id: reviewId },
    data: payload
  });
};
var deleteReview = async (reviewId, customerId) => {
  const review = await prisma.review.findUnique({
    where: { id: reviewId }
  });
  if (!review || review.customerId !== customerId) {
    throw new Error("Unauthorized or review not found");
  }
  return prisma.review.delete({
    where: { id: reviewId }
  });
};
var reviewService = {
  createReview,
  getReviewsByMeal,
  updateReview,
  deleteReview
};

// src/modules/review/review.controller.ts
var createReview2 = async (req, res) => {
  try {
    const customerId = req.user?.id;
    const result = await reviewService.createReview(req.body, customerId);
    res.status(201).json({
      success: true,
      message: "Review added successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getReviewsByMeal2 = async (req, res) => {
  try {
    const { mealId } = req.params;
    const result = await reviewService.getReviewsByMeal(mealId);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var updateReview2 = async (req, res) => {
  try {
    const customerId = req.user.id;
    const { id } = req.params;
    const result = await reviewService.updateReview(id, customerId, req.body);
    res.status(200).json({
      success: true,
      message: "Review updated successfully",
      data: result
    });
  } catch (error) {
    res.status(403).json({
      success: false,
      message: error.message
    });
  }
};
var deleteReview2 = async (req, res) => {
  try {
    const customerId = req.user.id;
    const { id } = req.params;
    await reviewService.deleteReview(id, customerId);
    res.status(200).json({
      success: true,
      message: "Review deleted successfully"
    });
  } catch (error) {
    res.status(403).json({
      success: false,
      message: error.message
    });
  }
};
var reviewController = {
  createReview: createReview2,
  getReviewsByMeal: getReviewsByMeal2,
  updateReview: updateReview2,
  deleteReview: deleteReview2
};

// src/modules/review/review.route.ts
var reviewRouter = express.Router();
reviewRouter.get("/meal/:mealId", reviewController.getReviewsByMeal);
reviewRouter.post("/", auth_default("CUSTOMER" /* customer */), reviewController.createReview);
reviewRouter.patch("/:id", auth_default("CUSTOMER" /* customer */), reviewController.updateReview);
reviewRouter.delete("/:id", auth_default("CUSTOMER" /* customer */), reviewController.deleteReview);
var review_route_default = reviewRouter;

// src/routes/index.ts
var routes = Router5();
routes.use("/user", user_route_default);
routes.use("/provider", provider_route_default);
routes.use("/provider/meal", meal_route_default);
routes.use("/order", order_route_default);
routes.use("/review", review_route_default);
var routes_default = routes;

// src/app.ts
import cookieParser from "cookie-parser";
var app = express2();
app.use(cors({
  origin: process.env.APP_URL || "http://localhost:3000",
  // client side url 
  credentials: true
}));
app.use(express2.json());
app.use(cookieParser());
app.use("/api/v1", routes_default);
app.get("/", (req, res) => {
  res.send("Hello from Alifs Apollo Gears World !");
});
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
